version: '3.7'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - mudaark_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mudaark_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mudaark
      POSTGRES_USER: mudaark
      POSTGRES_PASSWORD: mudaark
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mudaark_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - mudaark_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info -P eventlet
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
    networks:
      - mudaark_network

volumes:
  postgres_data:
  minio_data:

networks:
  mudaark_network:
    driver: bridge
